#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>

DIR="$HOME/.config/rofi"

## rofi sudo askpass helper
export SUDO_ASKPASS="$DIR"/scripts/askpass

## execute the application
sudo -A $1
